sudo: false
language: node_js
node_js:
  - '6'
  - '8'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
  - test $TRAVIS_NODE_VERSION = 8 && travis_wait ./doc_travis.sh

# jobs:
#   include:
#     - stage: deploy
#       node_js: '8'
#       script: ./after.sh